remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins

title: hyper thanatos
description: Athanasios Anagnostopoulos writes and creates moving images, staged situations, environments and atmospheres to promote memory and doubt.

show_downloads: false 
google_analytics: [Your Google Analytics tracking ID]
